### ISSUE TITLE
No images found

### ISSUE THREAD

**Issue by friedmanm1** [ififfy/flipflip#148]
I just started using FlipFlip, and I am very grateful for all the work that you have put into it. I am having a problem loading any sources from outside my own device. I can run a scene fine if I choose as my source "Add local files," but if I choose "Add URL," and insert an active tumblr or imagefap URL, I get the message "No images found." Can you give me any help in drawing from online sources? Thank you very much.

**Comment by GoddessServant0** [comment]
Hey @friedmanm1, thanks for checking out FlipFlip! I'll assume you're using the v2.0.0 version. I'm actually _just_ getting ready to release a new version (v2.1.0) today that should fix those issues for you (ImageFap wasn't implemented until v2.1.0 and Tumblr had an issue with all users sharing the same key, this has been fixed in v2.1.0)

Check back for a new version later today and see if that fixes your problem 😉

**Comment by GoddessServant0** [comment]
Check out the new release and let me know if that fixes the issue 😊 
https://github.com/ififfy/flipflip/releases/tag/v2.1.0

**Comment by friedmanm1** [comment]
Thank you very much for getting back to me, but unfortunately, my problem is not yet solved. I downloaded and installed the new release (2.1.0), and the program prompted me to allow access to Reddit. While on the config, I also allowed access to Tumblr, but when I try to run a scene with Tumblr URL's, the sites start to load, but then I get the error message, "I couldn't find anything." I wonder if you might have any other suggestions for me. Thanks again.


   On Monday, May 27, 2019, 6:17:04 PM EDT, GoddessServant0 <notifications@github.com> wrote:  
 
 
Check out the new release and let me know if that fixes the issue 😊
https://github.com/ififfy/flipflip/releases/tag/v2.1.0

**Comment by GoddessServant0** [comment]
🤦‍♀ This was totally my fault. The changes I made in v2.1.0 didn't stand up to scaled use 😅

I just put out a bugfix release [v2.1.1](https://github.com/ififfy/flipflip/releases/tag/v2.1.1) which adds a few more keys for public use, and lets you configure your own. If you need instructions on how to do so, [see here](https://github.com/ififfy/flipflip/wiki/FlipFlip-User-Manual#configuring-your-own-tumblr-api-keys).

That should fix the problem, but please let me know if you have any other issues 🙂

**Comment by friedmanm1** [comment]
For some reason, the URL's are working this morning, even without the bugfix. I think it may have something to do with the settings on my security software, which is interfering with the program's access to the internet.

    On Tuesday, May 28, 2019, 8:49:48 PM EDT, GoddessServant0 <notifications@github.com> wrote:  
 
 
🤦‍♀ This was totally my fault. The changes I made in v2.1.0 didn't stand up to scaled use 😅
 
I just put out a bugfix release v2.1.1 which adds a few more keys for public use, and lets you configure your own. If you need instructions on how to do so, see here.

That should fix the problem, but please let me know if you have any other issues 🙂

**Comment by GoddessServant0** [comment]
> For some reason, the URL's are working this morning

This is more likely because people started using their own keys now and Tumblr isn't blocking the default key(s) any longer. But I'm very happy it's working 👍
